package com.bvisionry.certificate.domain;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.Generated;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * A permanent, uniquely-numbered certificate awarded to a learner when they
 * complete a course.
 *
 * <p>Snapshots {@code courseTitle} and {@code learnerName} at issuance time so
 * the certificate remains accurate even if the underlying course or user record
 * is later modified. One certificate per enrollment (enforced by the
 * {@code uq_certificate_enrollment} unique constraint).
 *
 * <p>Entity style mirrors {@link com.bvisionry.catalog.domain.Content}: the
 * {@code id} is generated by the database via {@code gen_random_uuid()};
 * {@code issued_at} is set by the database default and also by
 * {@link #onPersist()}.
 */
@Entity
@Table(name = "certificate")
@Getter
@Setter
public class Certificate {

    @Id
    @Generated
    @ColumnDefault("gen_random_uuid()")
    @Column(name = "id", nullable = false, updatable = false, insertable = false)
    private UUID id;

    // The three FK columns are nullable: a certificate is a permanent snapshot
    // that outlives its enrollment/user/course. When any of those is hard-deleted
    // the DB FK (ON DELETE SET NULL, V85) nulls the reference here while the row
    // and its snapshot scalars (number, courseTitle, learnerName, issuedAt)
    // survive. unique=true on enrollment_id stays valid — Postgres treats NULLs
    // as distinct, so at most one cert per non-null enrollment is still enforced.
    @Column(name = "enrollment_id", nullable = true, unique = true, updatable = false)
    private UUID enrollmentId;

    @Column(name = "user_id", nullable = true, updatable = false)
    private UUID userId;

    @Column(name = "course_id", nullable = true, updatable = false)
    private UUID courseId;

    /** Unique human-readable identifier, e.g. {@code BV-2026-A3X9R2}. */
    @Column(name = "certificate_number", nullable = false, unique = true, length = 40, updatable = false)
    private String certificateNumber;

    /** Snapshot of the course title at time of issuance. */
    @Column(name = "course_title", nullable = false, length = 200)
    private String courseTitle;

    /** Snapshot of the learner's display name at time of issuance. */
    @Column(name = "learner_name", nullable = false, length = 200)
    private String learnerName;

    @Column(name = "issued_at", nullable = false, updatable = false)
    private OffsetDateTime issuedAt;

    @PrePersist
    void onPersist() {
        if (issuedAt == null) {
            issuedAt = OffsetDateTime.now();
        }
    }
}
