package com.bvisionry.notification.entity;

public enum EmailTemplateKey {
    ASSESSMENT_ASSIGNED,
    ASSESSMENT_REMINDER,
    RESULTS_READY,
    POST_ASSESSMENT_SURVEY_INVITE,
    INVITATION,
    PASSWORD_RESET,
    TRIAL_ENDING_SOON,
    TRIAL_EXPIRED,
    UPGRADE_REQUESTED,
    CONTACT_US,
    DEMO_REQUEST,
    SURVEY_GIFT_ASSESSMENT,
    LEAD_MAGNET
}
