-- V130: On-demand AI-use detection over a submission's free-text answers.
--
-- AI_USE_DETECTION — admin-editable system prompt for the detector (an LLM
-- judge that scores how likely the free-text answers were AI-generated).
-- submission_ai_detections — one stored result per submission, overwritten on
-- each admin re-run. The score is a heuristic confidence indicator, not proof;
-- the UI derives the verdict band from the score.

-- Keep the constraint list in sync with the PromptType enum.
ALTER TABLE prompt_templates DROP CONSTRAINT IF EXISTS prompt_templates_prompt_type_check;
ALTER TABLE prompt_templates ADD CONSTRAINT prompt_templates_prompt_type_check
    CHECK (prompt_type IN ('SYSTEM_PROMPT', 'TEAM_INSIGHT', 'OVERALL_SUMMARY', 'FREE_TIER_SUMMARY',
                           'PUBLIC_ASSESSMENT_SYSTEM_PROMPT', 'PROGRAM_COMPOSER', 'PROGRAM_COACH',
                           'AI_USE_DETECTION'));

INSERT INTO prompt_templates (id, prompt_type, content, created_at)
SELECT gen_random_uuid(),
       'AI_USE_DETECTION',
       'You are a forensic writing analyst. You judge how likely it is that the free-text answers in an '
       || 'assessment were generated by an AI assistant rather than written by the respondent. Weigh concrete '
       || 'linguistic signals: uniformly polished register across all answers, generic consultant-style phrasing '
       || 'with no personal or situational specifics, hedged both-sides framing, list-like or template-like '
       || 'structure inside prose answers, vocabulary and transitions typical of LLM output, and answers that '
       || 'restate the question before answering it. Weigh counter-signals too: typos, idiosyncratic grammar, '
       || 'concrete names, numbers and anecdotes, inconsistent register between answers, and very short or '
       || 'informal replies. Calibrate honestly: reserve scores above 75 for strong converging signals across '
       || 'multiple answers, and when there is too little text to judge, return a low score and say so in the '
       || 'rationale. Non-native phrasing alone is NEVER evidence of AI use. Your judgment is an indicator for '
       || 'a human reviewer, not proof — never present it as certainty.',
       now()
WHERE NOT EXISTS (SELECT 1 FROM prompt_templates WHERE prompt_type = 'AI_USE_DETECTION');

CREATE TABLE submission_ai_detections (
    id                  UUID PRIMARY KEY,
    submission_id       UUID NOT NULL UNIQUE REFERENCES submissions (id) ON DELETE CASCADE,
    ai_likelihood_score INT NOT NULL CHECK (ai_likelihood_score BETWEEN 0 AND 100),
    rationale           TEXT NOT NULL,
    -- JSON array of {qid, questionText, note} resolved at detection time so
    -- reads never need to re-join questions.
    answer_findings     TEXT,
    model               VARCHAR(200) NOT NULL,
    -- Prompt REVISION id that produced this result (audit/reproducibility,
    -- same semantics as pillar_evaluations provenance).
    prompt_version_id   UUID,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL
);
