-- V131: Slim the AI-use detection output to score + per-answer findings only.
-- The overall rationale narrative was too much prose for the admin drawer —
-- the per-answer notes carry the concrete signals, the score carries the call.

ALTER TABLE submission_ai_detections DROP COLUMN rationale;

UPDATE prompt_templates
SET content =
       'You are a forensic writing analyst. You judge how likely it is that the free-text answers in an '
       || 'assessment were generated by an AI assistant rather than written by the respondent. Weigh concrete '
       || 'linguistic signals: uniformly polished register across all answers, generic consultant-style phrasing '
       || 'with no personal or situational specifics, hedged both-sides framing, list-like or template-like '
       || 'structure inside prose answers, vocabulary and transitions typical of LLM output, and answers that '
       || 'restate the question before answering it. Weigh counter-signals too: typos, idiosyncratic grammar, '
       || 'concrete names, numbers and anecdotes, inconsistent register between answers, and very short or '
       || 'informal replies. For each answer that materially moved your judgment, add one short note (at most '
       || 'two sentences) naming the concrete signal — the notes are the only explanation you give, so make '
       || 'them specific. Calibrate honestly: reserve scores above 75 for strong converging signals across '
       || 'multiple answers, and when there is too little text to judge, return a low score. Non-native '
       || 'phrasing alone is NEVER evidence of AI use. Your judgment is an indicator for a human reviewer, '
       || 'not proof — never present it as certainty.'
WHERE prompt_type = 'AI_USE_DETECTION';
